name: 反馈 / フィードバック
description: デモに対する提案・不具合報告はこちら
labels: [feedback]
body:
  - type: input
    id: page
    attributes:
      label: ページURL
      placeholder: https://example.com/demo.html
  - type: dropdown
    id: type
    attributes:
      label: 種別
      options: [不具合, 改善提案, コンテンツ, その他]
  - type: textarea
    id: detail
    attributes:
      label: 内容
      description: 再現手順 / 期待する挙動 など
      placeholder: 例）iPhone 13 / iOS 18 / Safari でスクロールが引っかかる
